apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.app.syncWaves | quote }}
    argocd.argoproj.io/hook: {{ .Values.app.hook }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.app.path }}
    helm:
      valueFiles:
      - {{ .Values.app.values.dev }}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

   
