name: "Terraform Deploy"
description: "Runs Terraform init, workspace select, and apply with variables"

inputs:
  environment:
    required: true
  aws_access_key:
    required: true
  aws_secret_key:
    required: true
  region:
    required: true
  tf_state_bucket:
    required: true  

  aws_account_id:
    required: true
  cluster_name:
    required: true
  db_username:
    required: true
  db_name:
    required: true
  service_account_name:
    required: true
  directory:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4

  - uses: hashicorp/setup-terraform@v3

  - uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-access-key-id: ${{ inputs.aws_access_key }}
      aws-secret-access-key: ${{ inputs.aws_secret_key }}
      aws-region: ${{ inputs.region }}

  - name: Terraform Init
    working-directory: ${{inputs.directory}}
    shell: bash
    run: |
      terraform init -upgrade \
        -backend-config="bucket=${{ inputs.tf_state_bucket }}" \
        -backend-config="key=networking/terraform.tfstate" \
        -backend-config="region=${{ inputs.region }}" \
        -backend-config="dynamodb_table=terraform-locks" \
        -backend-config="encrypt=true"

  - name: Select Workspace
    working-directory: ${{inputs.directory}}
    shell: bash
    run: terraform workspace select -or-create=true ${{ inputs.environment }}

  - name: Terraform Apply
    working-directory: ${{inputs.directory}}
    shell: bash
    run: |
      terraform apply -auto-approve -input=false \
        -var="aws_account_id=${{ inputs.aws_account_id }}" \
        -var="region=${{ inputs.region }}" \
        -var="cluster_name=${{ inputs.cluster_name }}" \
        -var="db_username=${{ inputs.db_username }}" \
        -var="db_name=${{ inputs.db_name }}" \
        -var="service_account_name=${{ inputs.service_account_name }}" \
        -var="ENV_PREFIX=${{ inputs.environment }}"
