apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.certManagerCrd.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.certManagerCrd.syncWaves | quote }}
    argocd.argoproj.io/hook: {{ .Values.certManagerCrd.hook }}
spec:
  project: default
  source:
    repoURL: {{ .Values.certManagerCrd.repoURL }}
    chart: {{ .Values.certManagerCrd.chart }}
    targetRevision: {{ .Values.certManagerCrd.version }}
    helm:
      values: |
        crds:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.certManagerCrd.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m