apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.lokiCrd.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.lokiCrd.syncWaves | quote }}
    argocd.argoproj.io/hook: {{ .Values.lokiCrd.hook }}
spec:
  project: default
  source:
    repoURL: {{ .Values.lokiCrd.repoURL }}
    chart: {{ .Values.lokiCrd.chart }}
    targetRevision: {{ .Values.lokiCrd.version }}
    helm:
      values: |
        loki:
          useTestSchema: true
         

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.lokiCrd.namespace }} 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m