name: Load TF Outputs
description: Downloads Terraform outputs artifact and loads them into environment variables

runs:
  using: "composite"
  steps:
  - name: Download TF outputs artifact
    uses: actions/download-artifact@v4
    with:
      name: tf-outputs
      path: ./tf-data

  - name: Load TF outputs into env
    shell: bash
    run: |
      TF_OUTPUTS=./tf-data/tf-outputs.json

      IRSA_ARN=$(jq -r .irsa_arn "$TF_OUTPUTS")
      SECRETSMANAGER_ARN=$(jq -r .SecretsManager_arn "$TF_OUTPUTS")
      DB_INSTANCE_ADDRESS=$(jq -r .db_instance_address "$TF_OUTPUTS")
      DB_INSTANCE_NAME=$(jq -r .db_instance_name "$TF_OUTPUTS")
      DB_INSTANCE_PORT=$(jq -r .db_instance_port "$TF_OUTPUTS")
      FRONTEND_REPO_URL=$(jq -r .frontend_repository_url "$TF_OUTPUTS")
      BACKEND_REPO_URL=$(jq -r .backend_repository_url "$TF_OUTPUTS")

      echo "IRSA_ARN=$IRSA_ARN" >> $GITHUB_ENV
      echo "SECRETSMANAGER_ARN=$SECRETSMANAGER_ARN" >> $GITHUB_ENV
      echo "DB_INSTANCE_ADDRESS=$DB_INSTANCE_ADDRESS" >> $GITHUB_ENV
      echo "DB_INSTANCE_NAME=$DB_INSTANCE_NAME" >> $GITHUB_ENV
      echo "DB_INSTANCE_PORT=$DB_INSTANCE_PORT" >> $GITHUB_ENV
      echo "FRONTEND_REPO_URL=$FRONTEND_REPO_URL" >> $GITHUB_ENV
      echo "BACKEND_REPO_URL=$BACKEND_REPO_URL" >> $GITHUB_ENV
